name: web

on:
  push:
    branches:
      - master
    paths:
      - web/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web # sets the directory for "run" commands only
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Serverless Plugins
        run: serverless plugin install -n serverless-lift

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--prefer-dist --optimize-autoloader --no-dev"
          working-directory: web

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Serverless Deploy
        uses: serverless/github-action@v3
        with:
          args: -c "cd web && serverless deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

  sync-static-assets:
    runs-on: ubuntu-latest
    needs: build
    env:
      S3_IMAGES_DST: s3://wheelerrecommends-dev-cdnassetsa4271342-cfvrgwogz7ie/images/
      S3_IMAGES_SRC: s3://wheelerrecommends-static-assets/images/
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Sync Images
        run: aws s3 sync ${{ env.S3_IMAGES_SRC }} ${{ env.S3_IMAGES_DST }}
