name: web

on:
  push:
    branches:
      - master
    paths:
      - web/**

  workflow_dispatch:

env:
  S3_IMAGES_DST: s3://wheelerrecommends-dev-cdnassetsa4271342-cfvrgwogz7ie/images/
  S3_IMAGES_SRC: s3://wheelerrecommends-static-assets/images/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--prefer-dist --optimize-autoloader --no-dev"

      - name: Serverless Deploy
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync Static Images
        run: aws s3 sync ${{ env.S3_IMAGES_SRC }} ${{ env.S3_IMAGES_DST }}
