service: wheelerrecommends

custom:
  ACM_ARN: arn:aws:acm:us-east-1:${aws:accountId}:certificate/8c94bd47-f087-4aaf-b9fc-3f0c37fe7017
  CUSTOM_DOMAIN: wheelerrecommends.com
  ROUTE53_HOSTED_ZONE_ID: Z02692147JE4N4A19172

provider:
    name: aws
    region: us-east-1

plugins:
  - ./vendor/bref/bref
  - serverless-lift

functions:
    api:
        description: 'serverless php movie recommendation engine'
        handler: index.php
        runtime: php-83-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: 'GET /'

constructs:
  cdn:
    certificate: ${self:custom.ACM_ARN}
    redirectToMainDomain: true
    type: server-side-website
    assets:
      '/css/*': css/
      '/images/*': images/
      '/assets/*': assets/
      '/favicon/*': favicon/
    domain:
      - ${self:custom.CUSTOM_DOMAIN}
      - www.${self:custom.CUSTOM_DOMAIN}
    extensions:
      distribution:
        Properties:
          DistributionConfig:
            Comment: 'CDN for ${self:custom.CUSTOM_DOMAIN} ${sls:stage}'
            IPV6Enabled: true

resources:
  Resources:
    WorldWideWebIPv4:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: ${self:custom.ROUTE53_HOSTED_ZONE_ID}
        Name: www.${self:custom.CUSTOM_DOMAIN}
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # CloudFront Route53 HostedZoneId
          DNSName: ${construct:cdn.cname}
    WorldWideWebIPv6:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: ${self:custom.ROUTE53_HOSTED_ZONE_ID}
        Name: www.${self:custom.CUSTOM_DOMAIN}
        Type: AAAA
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # CloudFront Route53 HostedZoneId
          DNSName: ${construct:cdn.cname}
    ZoneApexIPv4:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: ${self:custom.ROUTE53_HOSTED_ZONE_ID}
        Name: ${self:custom.CUSTOM_DOMAIN}
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # CloudFront Route53 HostedZoneId
          DNSName: ${construct:cdn.cname}
    ZoneApexIPv6:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: ${self:custom.ROUTE53_HOSTED_ZONE_ID}
        Name: ${self:custom.CUSTOM_DOMAIN}
        Type: AAAA
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # CloudFront Route53 HostedZoneId
          DNSName: ${construct:cdn.cname}

# exclude
package:
    patterns:
        - '!css/**'
        - '!images/**'
        - '!assets/**'
        - '!favicon/**'
        - '!node_modules/**'
        - '!tests/**'
